### ISSUE TITLE
Ops Team Lead

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#101]
Docs: https://bisq.wiki/Ops_Team
Teams: @bisq-network/ops, @bisq-network/team-leads

**Comment by wiz** [comment]
## Initial Report

Ops Project board: https://github.com/bisq-network/ops/projects/1

Since we restructured the DAO into teams and established the Ops Team a few months ago, we've been working on decentralizing all the critical Bisq infrastructure in order to remove our reliance on TTP and CPOF, as well as increasing performance and usability. So far the current progress is:

- [X] Decentralize the Bisq Explorer https://github.com/bisq-network/proposals/issues/143
- [X] Decentralize the Bisq Mempool Fee Estimation https://github.com/bisq-network/projects/issues/37
- [X] Decentralize the Bisq Pricenode data source https://github.com/bisq-network/projects/issues/35
- [ ] Decentralize the Bisq Markets API https://github.com/bisq-network/projects/issues/41
- [ ] Decentralize the Bisq Domain Names https://github.com/bisq-network/proposals/issues/211

After the decentralization efforts are completed and things are running smoothly, looking to the longer term the next priority for Ops team will likely be researching how to get Bisq working on a Bitcoin Sidechain like Liquid in the event that Bitcoin TX fees skyrocket and result in Bisq trades becoming priced out of Bitcoin Base Layer. This was proposed in https://github.com/bisq-network/proposals/issues/198 and the project proposal will be forthcoming.

**Comment by cbeams** [comment]
Per @wiz's request, I've added @emzy as an assignee to this role issue, indicating that he is the secondary owner, with @wiz remaining the primary owner. See the similar change made to the Support Team Lead role documented at https://github.com/bisq-network/roles/issues/102#issuecomment-814151696.

**Comment by wiz** [comment]
I discussed with @Emzy today and we agreed that he would takeover the primary Ops Team Lead role from now on, and I would become the secondary backup - @cbeams could you please make the appropriate change?

**Comment by cbeams** [comment]
@wiz wrote:
> I discussed with @Emzy today and we agreed that he would takeover the primary Ops Team Lead role from now on, and I would become the secondary backup

Thanks, @wiz for all your efforts! And thanks, @Emzy for taking it on. 

> @cbeams could you please make the appropriate change?

Done. Both @bisq-network/ops and @bisq-network/team-leads teams have been updated accordingly.

**Comment by wiz** [comment]
I'm resigning to focus on @mempool - it's all up to @Emzy now :)

**Comment by Emzy** [comment]
Sad to see you leave the Ops Team role.
Thank you for all the past work!

**Comment by cbeams** [comment]
> I'm resigning to focus on @mempool - it's all up to @Emzy now :)

Cheers, @wiz—thanks for all you've done as ops lead over the ... years (!)
